export enum VehicleTypeCode {
  AUTO_2AXLES = '2AxlesAuto',
  AUTO_3AXLES = '3AxlesAuto',
  MOTORCYCLE_2AXLES = '2AxlesMotorcycle',
  MOTORCYCLE_3AXLES = '3AxlesMotorcycle',
  TRUCK_2AXLES = '2AxlesTruck',
  TRUCK_3AXLES = '3AxlesTruck',
  TRUCK_4AXLES = '4AxlesTruck',
  TRUCK_5AXLES = '5AxlesTruck',
  TRUCK_6AXLES = '6AxlesTruck',
  TRUCK_7AXLES = '7AxlesTruck',
  TRUCK_8AXLES = '8AxlesTruck',
  TRUCK_9AXLES = '9AxlesTruck',
  BUS_2AXLES = '2AxlesBus',
  BUS_3AXLES = '3AxlesBus',
  RV_2AXLES = '2AxlesRv',
  RV_3AXLES = '3AxlesRv',
  EV_2AXLES = '2AxlesEV',
}
