export enum TagSystem {
  IAVE = 'IAVE',
  TAG_PASE = 'TAG_PASE',
  TELEVIA = 'TELEVIA',
  VIAPASS = 'VIAPASS',
  SIGO = 'SIGO',
  TELEPEAJE_CHIHUAHUA = 'TELEPEAJE_CHIHUAHUA',
  TAG_QUICKPASS = 'TAG_QUICKPASS',
}
