export enum AuditEventType {
  LOGIN = 'LOGIN',
  LOGIN_FAILED = 'LOGIN_FAILED',
  REGISTER = 'REGISTER',
  LOGOUT = 'LOGOUT',
  CALCULATE_TOLL = 'CALCULATE_TOLL',
  COMPARE_ROUTES = 'COMPARE_ROUTES',
  VEHICLE_CREATED = 'VEHICLE_CREATED',
  VEHICLE_UPDATED = 'VEHICLE_UPDATED',
  VEHICLE_DELETED = 'VEHICLE_DELETED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
}
